export const DEFAULT_STATE = {
  kids: ['Ella', 'Finn'],
  scores: { Ella: 7, Finn: 4 },
  weekScores: { Ella: 7, Finn: 4 },
  log: [],
  meals: [
    { day: 'Mon', name: 'Spaghetti bolognese', time: '30 min' },
    { day: 'Tue', name: 'Grilled chicken & rice', time: '25 min' },
    { day: 'Wed', name: 'Veggie stir fry', time: '20 min' },
    { day: 'Thu', name: 'Fish tacos', time: '35 min' },
    { day: 'Fri', name: 'Homemade pizza', time: '45 min' },
    { day: 'Sat', name: 'Lamb chops & roasted veg', time: '40 min' },
    { day: 'Sun', name: 'Roast chicken', time: '90 min' },
  ],
  shop: {
    Produce: [
      { name: 'Onions', qty: '4', done: false },
      { name: 'Garlic', qty: '1 head', done: false },
      { name: 'Courgette', qty: '2', done: true },
      { name: 'Cherry tomatoes', qty: '250 g', done: false },
      { name: 'Limes', qty: '4', done: false },
    ],
    'Meat & fish': [
      { name: 'Minced beef', qty: '600 g', done: false },
      { name: 'Chicken thighs', qty: '8', done: false },
      { name: 'Cod fillets', qty: '4', done: false },
      { name: 'Lamb chops', qty: '6', done: false },
    ],
    Pantry: [
      { name: 'Spaghetti', qty: '500 g', done: true },
      { name: 'Tinned tomatoes', qty: '3 cans', done: false },
      { name: 'Jasmine rice', qty: '1 kg', done: false },
      { name: 'Taco shells', qty: '1 pack', done: false },
    ],
    Dairy: [
      { name: 'Mozzarella', qty: '200 g', done: false },
      { name: 'Cheddar', qty: '150 g', done: false },
    ],
    Frozen: [],
    Other: [],
  },
  rewards: [
    { pts: 5, label: '30 min extra TV' },
    { pts: 10, label: '1 hr computer games' },
    { pts: 15, label: 'Stay up 30 min later' },
    { pts: 20, label: 'Choose Friday dinner' },
    { pts: 25, label: 'Movie night pick' },
    { pts: 35, label: 'Friend sleepover' },
  ],
  profiles: {
    Ella: { role: 'child', age: null, allergies: [], dislikes: [], notes: '' },
    Finn: { role: 'child', age: null, allergies: [], dislikes: [], notes: '' },
  },
  prefs: {
    cuisines: '',
    time: '30–45 min',
    weekend: 'Happy to cook more',
    avoid: '',
    ptsRules: '',
  },
  mealNotes: '',
  lastMealDay: 'Monday',
  chatHistory: [],
};
